name: Feature Request
description: Propose a new feature for ExoVote
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you'd like to add to ExoVote.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature and what problem it solves.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be considered done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Frontend
        - Backend
        - Infrastructure
        - Full Stack
        - Design
        - Compliance
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: Design / Mockups
      description: Any visual references, mockups, or wireframes.
    validations:
      required: false

  - type: textarea
    id: technical
    attributes:
      label: Technical Notes
      description: Implementation hints, affected files, dependencies.
    validations:
      required: false
