languages:
- csharp
- typescript

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

initial_prompt: ""

project_name: "exovote"

included_optional_tools: []

base_modes:

default_modes:

fixed_tools: []
